# -*- coding: utf-8 -*-
"""ML_Ch4.1 - kMeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_f2W9IeYIm5fecrJ9KTlHaGqgC10lB1r

# DEMO 4.1: **kMeans**
<u>Nội dung</u>:
1. Customer segmentation
2. Biểu diễn trực quan kết quả gom cụm (2D)

<u>Cập nhật</u>: **04/2023**

---
### **MÔI TRƯỜNG TRIỂN KHAI ỨNG DỤNG**
---
"""

## Môi trường lập trình
from google.colab import drive
drive.mount("/content/gdrive")
folder = '/content/gdrive/My Drive/Edu/1. UEH/Machine Learning/Demo/Ch04 - Unsupervised Learning'

## Thư viện
import joblib             as jlb
import matplotlib.pyplot  as plt
import numpy              as np
import pandas             as pd
import seaborn            as sbn
import warnings
warnings.filterwarnings('ignore') # tắt những cảnh báo

from collections          import Counter
from sklearn.cluster      import KMeans

"""---
## 1. **Customer segmentation**
---
"""

## Tập tin dữ liệu Shopping.csv
data = pd.read_csv(folder + '/Data/Shopping.csv')
print(data.head())

## Quan sát sơ bộ dữ liệu
print(data.groupby('Genre').Age.count())

## Chuyển thuộc tính [Genre] sang dạng số
data = pd.get_dummies(data, drop_first = True) # thuộc tính nhị phân nên có thể bỏ 1 cột
print(data.head())

##------------------------------------------------------------------------------
## Xây dựng mô hình kMeans
##------------------------------------------------------------------------------
k     = 5
model = KMeans(n_clusters = k)
model.fit(data)  # xây dựng mô hình

## Lưu trữ mô hình để khai thác về sau
jlb.dump(model, folder + '/Output/kMeans.mdl')

## Khai thác mô hình đã được xây dựng
model = jlb.load(folder + '/Output/kMeans.mdl')

## Các trọng tâm
print(f'*** {k} trọng tâm:')
print(model.cluster_centers_)

## Kết quả gom cụm khách hàng
data['cluster'] = model.labels_
print(data.head(10))

print('\nKích thước các clusters:', Counter(model.labels_))
print('\n2 clusters lớn nhất:', Counter(model.labels_).most_common(2))

"""---
## 2. **Biểu diễn trực quan kết quả gom cụm (2D)**
---
"""

## Tập tin dữ liệu Shopping.csv
data = pd.read_csv(folder + '/Data/Shopping.csv', usecols = ['Annual Income', 'Age'])

## Xây dựng mô hình kMeans
k     = 4
model = KMeans(n_clusters = k)
model.fit(data)

## Kết quả gom cụm khách hàng
centroids       = model.cluster_centers_
data['cluster'] = model.labels_
print(data.head(10))

print('\nKích thước các clusters:', Counter(model.labels_))
print('\nClusters lớn nhất:', Counter(model.labels_).most_common(1))

## Biểu diễn trực quan
plt.figure(figsize = (8, 8))
plt.scatter(centroids[:, 0], centroids[:, 1], marker = "s", s = 50, color = 'r')
plt.scatter(data.Age, data['Annual Income'], c = data.cluster)
plt.xlabel("Age")
plt.ylabel("Income")
plt.title("K-Means Customer Segmentation", color = "blue")
plt.show()